log:
  level: debug

secrets:
  session:
    - some-not-very-secure-secret

urls:
  mfa_ui: http://127.0.0.1/to-be-implemented
  login_ui: >-
    http://console.cloud.ory.local/auth/login
  registration_ui: >-
    http://console.cloud.ory.local/auth/registration
  default_return_to: >-
    http://console.cloud.ory.local/
  error_ui: >-
    http://console.cloud.ory.local/hive/error
  self:
    public: >-
      http://console.cloud.ory.local/.ory/hive/public/
    admin: >-
      http://api.cloud.ory.local/projects/ory/services/hive/admin/
  whitelisted_return_to_domains: ["http://console.cloud.ory.local/"]