log:
  level: debug

courier:
  smtp:
    connection_uri: smtp://foo:bar@baz/

secrets:
  session:
    - some-not-very-secure-secret

serve:
  admin:
    port: 4434
    host: 0.0.0.0
  public:
    port: 4433
    host: 0.0.0.0

dsn: postgres://postgres:secret@localhost:5432/kratos_dev?sslmode=disable

identity:
  traits:
    default_schema_url: http://127.0.0.1:4435/identity.schema.json

hashers:
  argon2:
    memory: 1048576
    iterations: 2
    parallelism: 4
    salt_length: 16
    key_length: 32

urls:
  mfa_ui: http://127.0.0.1:4435/to-be-implemented
  login_ui: http://127.0.0.1:4435/auth/login
  registration_ui: http://127.0.0.1:4435/auth/registration
  default_return_to: http://127.0.0.1:4436/
  error_ui: http://127.0.0.1:4435/error
  profile_ui: http://127.0.0.1:4435/profile
  self:
    public: http://127.0.0.1:4433/
    admin: http://127.0.0.1:4434/
  whitelisted_return_to_domains:
    - http://127.0.0.1:4436/

selfservice:
  strategies:
    password:
      enabled: true
    oidc:
      enabled: true
      config:
        providers:
          - id: github
            provider: github
            client_id: a
            client_secret: b
            schema_url: http://test.kratos.ory.sh/default-identity.schema.json
  logout:
    redirect_to: http://127.0.0.1:4435/
  login:
    request_lifespan: 99m
    before:
      - run: redirect
        config:
          default_redirect_url: http://127.0.0.1:4435/
          allow_user_defined_redirect: false
    after:
      password:
        - run: revoke_active_sessions
        - run: session
        - run: redirect
          config:
            default_redirect_url: http://127.0.0.1:4435/
            allow_user_defined_redirect: true
      oidc:
        - run: revoke_active_sessions
        - run: session
        - run: redirect
          config:
            default_redirect_url: http://127.0.0.1:4435/
            allow_user_defined_redirect: true
  registration:
    request_lifespan: 98m
    before:
      - run: redirect
        config:
          default_redirect_url: http://127.0.0.1:4435/
          allow_user_defined_redirect: false
    after:
      password:
        - run: session
        - run: redirect
          config:
            default_redirect_url: http://127.0.0.1:4435/
            allow_user_defined_redirect: true
      oidc:
        - run: session
        - run: redirect
          config:
            default_redirect_url: http://127.0.0.1:4435/
            allow_user_defined_redirect: true